### ISSUE TITLE
Cannot read property 'uglify' of undefined

### ISSUE THREAD

**Issue by Create-Peace** [jiechud/taro-mall#12]
at ImportDeclaration (/Users/apple/.config/yarn/global/node_modules/@tarojs/cli/dist/mini/astProcess.js:384:63)
    at NodePath._call (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/apple/.config/yarn/global/node_modules/babel-traverse/lib/context.js:150:16)

**Comment by wizard-a** [comment]
taro 是 2.0 吗

**Comment by Create-Peace** [comment]
Taro v1.3.0

**Comment by wizard-a** [comment]
Taro 升级下

**Comment by wizard-a** [comment]
Taro 升级下
